WebSocket implementation zio-quickstart.g8
ScalaConsultants/zio-quickstart.g8 pull request #4
Opened 2021-08-19 21:04 UTC by ernestochero

2021-08-28 08:15 UTC, sviezypan requested changes
hi @ernestochero, I added few minor comments. 
One way to verify that template is fine is to "cd" into dir where zio-quickstart is cloned and do
g8 file://zio-quickstart.g8
Then you can see if generated projects builds & runs.

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberService.scala$endif$
> +package com.example.service
this one needs to be package $package$.service

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberService.scala$endif$
> +object SubscriberService {
lets use optional braces syntax so we're consistent across codebase :)

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberServiceLive.scala$endif$
> +package com.example.service
also $package$.service, real package name will be specified by user

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberServiceLive.scala$endif$
> +final case class SubscriberServiceLive(deletedEventsSubscribers: Ref[List[Queue[ItemId]]])
lets use optional braces here and in companion object as well

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/test/scala/$package$/api/$if(add_websocket_endpoint.truthy)$WebSocketRouteSpec.scala$endif$
> +package com.example.api
$package$.api + optional braces syntax in this file

2021-08-28 08:15 UTC, sviezypan commented on src/main/g8/src/test/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberSpec.scala$endif$
> +package com.example.service
$package$.api + optional braces syntax in this file

2021-08-31 17:28 UTC, sviezypan approved these changes
Looks good to me!

2021-09-02 12:23 UTC, jczuchnowski commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberServiceLive.scala$endif$
> +import zio.stream.*
`_`

2021-09-02 12:25 UTC, jczuchnowski commented on src/main/g8/src/main/scala/$package$/service/$if(add_websocket_endpoint.truthy)$SubscriberServiceLive.scala$endif$
> +  override def showDeleteEvents: Stream[Nothing, ItemId] = ZStream.unwrap {
add newline between methods

2021-09-06 11:56 UTC, jczuchnowski approved these changes

2021-09-06 14:47 UTC, merged